import GlassCard from "./GlassCard";

type FeedbackCardProps = {
  feedback: string;
};

export default function FeedbackCard({ feedback }: FeedbackCardProps) {
  const sections = {
    summary: "",
    strengths: "",
    improvement: "",
  };

  const lines = feedback.split("\n");
  let currentSection: "summary" | "strengths" | "improvement" | null = null;

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.toLowerCase().startsWith("overall summary:")) {
      currentSection = "summary";
      continue;
    } else if (trimmed.toLowerCase().startsWith("strengths:")) {
      currentSection = "strengths";
      continue;
    } else if (
      trimmed.toLowerCase().startsWith("areas for improvement:") ||
      trimmed.toLowerCase().startsWith("areas improvement:") ||
      trimmed.toLowerCase().startsWith("improvement areas:")
    ) {
      currentSection = "improvement";
      continue;
    }

    if (currentSection) {
      sections[currentSection] += line + "\n";
    }
  }

  // If parsing resulted in completely empty sections, fallback to displaying
  // the raw feedback text under the Overall Summary block.
  const hasParsedContent =
    sections.summary.trim() || sections.strengths.trim() || sections.improvement.trim();

  const summary = hasParsedContent ? sections.summary.trim() : feedback.trim();
  const strengths = sections.strengths.trim();
  const improvement = sections.improvement.trim();

  return (
    <GlassCard className="p-6 text-slate-50 space-y-6">
      <div className="border-b border-white/10 pb-3">
        <h3 className="text-xl font-semibold tracking-tight text-white">
          AI Vocal Coach Analysis
        </h3>
        <p className="text-xs text-white/50">Personalized feedback generated by Gemma 3</p>
      </div>

      <div className="space-y-5">
        {summary && (
          <div className="space-y-1">
            <h4 className="text-xs font-bold uppercase tracking-wider text-sky-400">
              Overall Summary
            </h4>
            <p className="text-sm leading-relaxed text-slate-200 whitespace-pre-line">
              {summary}
            </p>
          </div>
        )}

        {strengths && (
          <div className="space-y-1">
            <h4 className="text-xs font-bold uppercase tracking-wider text-emerald-400">
              Strengths
            </h4>
            <p className="text-sm leading-relaxed text-slate-200 whitespace-pre-line">
              {strengths}
            </p>
          </div>
        )}

        {improvement && (
          <div className="space-y-1">
            <h4 className="text-xs font-bold uppercase tracking-wider text-rose-400">
              Areas For Improvement
            </h4>
            <p className="text-sm leading-relaxed text-slate-200 whitespace-pre-line">
              {improvement}
            </p>
          </div>
        )}
      </div>
    </GlassCard>
  );
}